export const ADMIN_ROLES = [
  "SUPER_ADMIN",
  "ADMIN",
  "INVENTORY_MANAGER",
  "ORDER_FULFILLMENT",
  "CUSTOMER_SUPPORT",
  "MARKETING",
  "ACCOUNTANT",
  "MODERATOR",
  "FINANCE",
  "CONTENT_MANAGER",
  "SUPPLIER_MANAGER",
] as const;

export type AdminRole = (typeof ADMIN_ROLES)[number];

export const ADMIN_ROLE_LABELS: Record<AdminRole, string> = {
  SUPER_ADMIN: "Super Admin",
  ADMIN: "Admin",
  INVENTORY_MANAGER: "Inventory Manager",
  ORDER_FULFILLMENT: "Order Fulfillment",
  CUSTOMER_SUPPORT: "Customer Support",
  MARKETING: "Marketing",
  ACCOUNTANT: "Accountant",
  MODERATOR: "Moderator",
  FINANCE: "Finance",
  CONTENT_MANAGER: "Content Manager",
  SUPPLIER_MANAGER: "Supplier Manager",
};

export const PERMISSIONS = [
  "dashboard:read",
  "products:read",
  "products:write",
  "products:approve",
  "categories:read",
  "categories:write",
  "orders:read",
  "orders:write",
  "refunds:read",
  "refunds:write",
  "payments:read",
  "customers:read",
  "customers:write",
  "suppliers:read",
  "suppliers:write",
  "inventory:read",
  "inventory:write",
  "purchases:read",
  "purchases:write",
  "shipping:read",
  "shipping:write",
  "content:read",
  "content:write",
  "marketing:read",
  "marketing:write",
  "reviews:read",
  "reviews:write",
  "analytics:read",
  "support:read",
  "support:write",
  "settings:read",
  "settings:write",
  "audit:read",
  "admins:read",
  "admins:write",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const ROLE_PERMISSIONS: Record<AdminRole, Permission[] | ["*"]> = {
  SUPER_ADMIN: ["*"],
  ADMIN: [
    "dashboard:read",
    "products:read",
    "products:write",
    "products:approve",
    "categories:read",
    "categories:write",
    "orders:read",
    "orders:write",
    "refunds:read",
    "refunds:write",
    "payments:read",
    "customers:read",
    "suppliers:read",
    "suppliers:write",
    "inventory:read",
    "inventory:write",
    "purchases:read",
    "purchases:write",
    "shipping:read",
    "content:read",
    "content:write",
    "marketing:read",
    "reviews:read",
    "reviews:write",
    "analytics:read",
    "support:read",
    "support:write",
    "settings:read",
    "audit:read",
  ],
  MODERATOR: [
    "dashboard:read",
    "products:read",
    "products:approve",
    "reviews:read",
    "reviews:write",
    "content:read",
  ],
  CUSTOMER_SUPPORT: [
    "dashboard:read",
    "orders:read",
    "orders:write",
    "customers:read",
    "support:read",
    "support:write",
    "refunds:read",
  ],
  FINANCE: [
    "dashboard:read",
    "payments:read",
    "refunds:read",
    "refunds:write",
    "analytics:read",
  ],
  CONTENT_MANAGER: [
    "content:read",
    "content:write",
    "categories:read",
    "marketing:read",
    "marketing:write",
  ],
  SUPPLIER_MANAGER: [
    "suppliers:read",
    "suppliers:write",
    "inventory:read",
    "inventory:write",
    "purchases:read",
    "purchases:write",
    "products:read",
    "products:approve",
  ],
  INVENTORY_MANAGER: [
    "dashboard:read",
    "inventory:read",
    "inventory:write",
    "products:read",
    "products:write",
    "suppliers:read",
    "purchases:read",
    "purchases:write",
  ],
  ORDER_FULFILLMENT: [
    "dashboard:read",
    "orders:read",
    "orders:write",
    "shipping:read",
    "shipping:write",
  ],
  MARKETING: [
    "dashboard:read",
    "marketing:read",
    "marketing:write",
    "content:read",
    "content:write",
    "reviews:read",
    "analytics:read",
  ],
  ACCOUNTANT: [
    "dashboard:read",
    "payments:read",
    "refunds:read",
    "refunds:write",
    "analytics:read",
    "settings:read",
  ],
};

export const PRODUCT_STATUSES = ["DRAFT", "PUBLISHED", "HIDDEN", "ARCHIVED", "OUT_OF_STOCK"] as const;
export const APPROVAL_STATUSES = ["PENDING", "APPROVED", "REJECTED"] as const;
export const PO_STATUSES = ["DRAFT", "ORDERED", "PARTIAL", "RECEIVED", "CANCELLED"] as const;
export const PO_PAYMENT_STATUSES = ["PENDING", "PARTIAL", "PAID"] as const;
export const RETURN_STATUSES = ["REQUESTED", "APPROVED", "REJECTED", "RECEIVED", "REFUNDED", "REPLACED"] as const;
export const SUPPLIER_STATUSES = ["ACTIVE", "INACTIVE", "ON_HOLD"] as const;
export const ORDER_STATUSES = [
  "PENDING",
  "CONFIRMED",
  "PACKED",
  "READY_TO_SHIP",
  "SHIPPED",
  "OUT_FOR_DELIVERY",
  "DELIVERED",
  "CANCELLED",
  "RETURNED",
  "REFUNDED",
] as const;
