export const ADMIN_ROLES = [
  "SUPER_ADMIN",
  "ADMIN",
  "MODERATOR",
  "CUSTOMER_SUPPORT",
  "FINANCE",
  "CONTENT_MANAGER",
  "SELLER_MANAGER",
] as const;

export type AdminRole = (typeof ADMIN_ROLES)[number];

export const PERMISSIONS = [
  "dashboard:read",
  "products:read",
  "products:write",
  "products:approve",
  "categories:read",
  "categories:write",
  "orders:read",
  "orders:write",
  "refunds:read",
  "refunds:write",
  "payments:read",
  "customers:read",
  "customers:write",
  "sellers:read",
  "sellers:write",
  "content:read",
  "content:write",
  "marketing:read",
  "marketing:write",
  "reviews:read",
  "reviews:write",
  "analytics:read",
  "support:read",
  "support:write",
  "settings:read",
  "settings:write",
  "audit:read",
  "admins:read",
  "admins:write",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const ROLE_PERMISSIONS: Record<AdminRole, Permission[] | ["*"]> = {
  SUPER_ADMIN: ["*"],
  ADMIN: [
    "dashboard:read",
    "products:read",
    "products:write",
    "products:approve",
    "categories:read",
    "categories:write",
    "orders:read",
    "orders:write",
    "refunds:read",
    "refunds:write",
    "payments:read",
    "customers:read",
    "sellers:read",
    "sellers:write",
    "content:read",
    "content:write",
    "marketing:read",
    "reviews:read",
    "reviews:write",
    "analytics:read",
    "support:read",
    "support:write",
    "settings:read",
    "audit:read",
  ],
  MODERATOR: [
    "dashboard:read",
    "products:read",
    "products:approve",
    "reviews:read",
    "reviews:write",
    "content:read",
  ],
  CUSTOMER_SUPPORT: [
    "dashboard:read",
    "orders:read",
    "orders:write",
    "customers:read",
    "support:read",
    "support:write",
    "refunds:read",
  ],
  FINANCE: [
    "dashboard:read",
    "payments:read",
    "refunds:read",
    "refunds:write",
    "analytics:read",
  ],
  CONTENT_MANAGER: [
    "content:read",
    "content:write",
    "categories:read",
    "marketing:read",
    "marketing:write",
  ],
  SELLER_MANAGER: [
    "sellers:read",
    "sellers:write",
    "products:read",
    "products:approve",
  ],
};

export const PRODUCT_STATUSES = ["DRAFT", "PUBLISHED", "HIDDEN", "ARCHIVED", "OUT_OF_STOCK"] as const;
export const APPROVAL_STATUSES = ["PENDING", "APPROVED", "REJECTED"] as const;
export const ORDER_STATUSES = [
  "PENDING",
  "CONFIRMED",
  "PACKED",
  "READY_TO_SHIP",
  "SHIPPED",
  "OUT_FOR_DELIVERY",
  "DELIVERED",
  "CANCELLED",
  "RETURNED",
  "REFUNDED",
] as const;
