import type { Product } from "./types";

export const PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "Cloud Vessel",
    slug: "cloud-vessel",
    brandId: "b1",
    price: 68,
    category: "home",
    tags: ["sculptural", "minimal", "soft"],
    mood: "calm",
    materials: ["ceramic", "glaze"],
    colors: ["ivory", "dusty blue"],
    vibe: "soft brutalism",
    description:
      "Hand-thrown ceramic with an impossible curve — like holding a slow exhale. Each piece is unique, with subtle variations in form and glaze.",
    images: [
      "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1200&q=80",
      "https://images.unsplash.com/photo-1610701596007-79502196bb30?w=1200&q=80",
    ],
    inStock: true,
    rating: 4.9,
    reviewCount: 47,
    featured: true,
    newArrival: true,
  },
  {
    id: "p2",
    name: "Midnight Taper Set",
    slug: "midnight-taper-set",
    brandId: "b2",
    price: 34,
    category: "lighting",
    tags: ["vintage", "dreamy", "cozy"],
    mood: "romantic",
    materials: ["beeswax", "cotton wick"],
    colors: ["royal blue", "ivory"],
    vibe: "candlelit nostalgia",
    description: "Indigo-dipped beeswax tapers that burn like a memory you can't place.",
    images: ["https://images.unsplash.com/photo-1602874801006-4f8a22944a3a?w=1200&q=80"],
    inStock: true,
    rating: 4.8,
    reviewCount: 112,
    featured: true,
  },
  {
    id: "p3",
    name: "Moss Journal",
    slug: "moss-journal",
    brandId: "b3",
    price: 28,
    category: "stationery",
    tags: ["botanical", "minimal", "artisan"],
    mood: "earthy",
    materials: ["linen", "cotton paper"],
    colors: ["sage", "ivory"],
    vibe: "forest floor energy",
    description: "Linen-bound pages with deckled edges. For thoughts that grow slowly.",
    images: ["https://images.unsplash.com/photo-1531346878377-a5be20842fd0?w=1200&q=80"],
    inStock: true,
    rating: 4.7,
    reviewCount: 89,
    newArrival: true,
  },
  {
    id: "p4",
    name: "Pearl Drop Earrings",
    slug: "pearl-drop-earrings",
    brandId: "b4",
    price: 92,
    compareAtPrice: 118,
    category: "wearables",
    tags: ["dreamy", "soft", "artisan"],
    mood: "romantic",
    materials: ["baroque pearl", "sterling silver"],
    colors: ["pearl", "silver"],
    vibe: "moonlit minimal",
    description: "Baroque pearls on brushed silver — irregular on purpose.",
    images: ["https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=1200&q=80"],
    inStock: true,
    rating: 5.0,
    reviewCount: 34,
    featured: true,
  },
  {
    id: "p5",
    name: "Sage & Sea Salt",
    slug: "sage-sea-salt",
    brandId: "b5",
    price: 56,
    category: "fragrance",
    tags: ["botanical", "cozy", "minimal"],
    mood: "calm",
    materials: ["soy wax", "essential oils"],
    colors: ["sage green"],
    vibe: "coastal calm",
    description: "A room that smells like a window left open after rain.",
    images: ["https://images.unsplash.com/photo-1541643600914-78b084683601?w=1200&q=80"],
    inStock: true,
    rating: 4.6,
    reviewCount: 203,
  },
  {
    id: "p6",
    name: "Weighted Silk Eye Mask",
    slug: "weighted-silk-eye-mask",
    brandId: "b6",
    price: 44,
    category: "wellness",
    tags: ["soft", "cozy", "dreamy"],
    mood: "calm",
    materials: ["mulberry silk", "lavender seeds"],
    colors: ["dusty blue", "ivory"],
    vibe: "sleep as ritual",
    description: "Cool-touch silk with lavender seed weight. Dreams optional.",
    images: ["https://images.unsplash.com/photo-1515377901643-4697fd6f54c9?w=1200&q=80"],
    inStock: true,
    rating: 4.9,
    reviewCount: 156,
    featured: true,
  },
  {
    id: "p7",
    name: "Arc Floor Lamp",
    slug: "arc-floor-lamp",
    brandId: "b2",
    price: 240,
    category: "lighting",
    tags: ["sculptural", "minimal", "vintage"],
    mood: "modern",
    materials: ["brushed steel", "linen shade"],
    colors: ["steel", "ivory"],
    vibe: "gallery at home",
    description: "A single arc of brushed steel — light as sculpture, not utility.",
    images: ["https://images.unsplash.com/photo-1507473889451-b8932f4a0b2c?w=1200&q=80"],
    inStock: true,
    rating: 4.8,
    reviewCount: 28,
  },
  {
    id: "p8",
    name: "Terracotta Diffuser",
    slug: "terracotta-diffuser",
    brandId: "b5",
    price: 38,
    category: "fragrance",
    tags: ["artisan", "botanical", "vintage"],
    mood: "earthy",
    materials: ["unglazed terracotta"],
    colors: ["terracotta"],
    vibe: "sun-baked earth",
    description: "Unglazed terracotta that holds scent like warm skin.",
    images: ["https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=1200&q=80"],
    inStock: true,
    rating: 4.5,
    reviewCount: 67,
  },
  {
    id: "p9",
    name: "Linen Throw",
    slug: "linen-throw",
    brandId: "b6",
    price: 118,
    category: "home",
    tags: ["cozy", "soft", "minimal"],
    mood: "calm",
    materials: ["belgian linen"],
    colors: ["natural ivory"],
    vibe: "slow mornings",
    description: "Undyed Belgian linen — gets softer every year you keep it.",
    images: ["https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=1200&q=80"],
    inStock: true,
    rating: 4.9,
    reviewCount: 91,
    newArrival: true,
  },
  {
    id: "p10",
    name: "Crystal Water Bottle",
    slug: "crystal-water-bottle",
    brandId: "b6",
    price: 52,
    category: "wellness",
    tags: ["dreamy", "sculptural", "botanical"],
    mood: "modern",
    materials: ["borosilicate glass", "rose quartz"],
    colors: ["clear", "rose"],
    vibe: "wellness witch",
    description: "Rose quartz chamber. Hydration with intention.",
    images: ["https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=1200&q=80"],
    inStock: true,
    rating: 4.4,
    reviewCount: 44,
  },
  {
    id: "p11",
    name: "Brass Bookmark",
    slug: "brass-bookmark",
    brandId: "b3",
    price: 22,
    category: "stationery",
    tags: ["vintage", "artisan", "minimal"],
    mood: "calm",
    materials: ["brass"],
    colors: ["brass"],
    vibe: "quiet luxury",
    description: "Hand-cut brass leaf that ages with your reading list.",
    images: ["https://images.unsplash.com/photo-1512820790803-83ca734da794?w=1200&q=80"],
    inStock: true,
    rating: 4.8,
    reviewCount: 178,
  },
  {
    id: "p12",
    name: "Sheer Layered Scarf",
    slug: "sheer-layered-scarf",
    brandId: "b4",
    price: 76,
    category: "wearables",
    tags: ["soft", "dreamy", "minimal"],
    mood: "romantic",
    materials: ["organza silk"],
    colors: ["dusty blue", "ivory"],
    vibe: "ethereal layers",
    description: "Two-tone organza that catches light like fog over water.",
    images: ["https://images.unsplash.com/photo-1520903920243-00d4a0a86fe1?w=1200&q=80"],
    inStock: true,
    rating: 4.7,
    reviewCount: 52,
  },
];

export const CATEGORY_LABELS: Record<Product["category"], string> = {
  home: "Home",
  wellness: "Wellness",
  stationery: "Stationery",
  wearables: "Wear",
  lighting: "Lighting",
  fragrance: "Fragrance",
  art: "Art",
  kitchen: "Kitchen",
};

export const FILTER_OPTIONS: { id: Product["category"] | "all"; label: string }[] = [
  { id: "all", label: "All" },
  { id: "home", label: "Home" },
  { id: "wellness", label: "Wellness" },
  { id: "stationery", label: "Paper" },
  { id: "wearables", label: "Wear" },
  { id: "lighting", label: "Light" },
  { id: "fragrance", label: "Scent" },
];

export function getProduct(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id || p.slug === id);
}

export function getProductsByCategory(category: Product["category"] | "all"): Product[] {
  if (category === "all") return PRODUCTS;
  return PRODUCTS.filter((p) => p.category === category);
}

export function getFeaturedProducts(): Product[] {
  return PRODUCTS.filter((p) => p.featured);
}

export function getNewArrivals(): Product[] {
  return PRODUCTS.filter((p) => p.newArrival);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return PRODUCTS.filter(
    (p) =>
      p.id !== product.id &&
      (p.category === product.category || p.tags.some((t) => product.tags.includes(t)))
  ).slice(0, limit);
}
